using System.IO.Compression;
using System.Text;
using Nexus.PLM.Addin.Sdk.Translators;
using Nexus.PLM.Addin.Sdk.Translators.Testing;
using Xunit;

namespace Nexus.PLM.OrcaSlicer.Translators.Tests;

/// <summary>Contract tests per translator.</summary>
public class ThreeMfToObjContractTests : TranslatorContractTests<ThreeMfToObjTranslator> { }

/// <summary>See <see cref="ThreeMfToObjContractTests"/>.</summary>
public class ThreeMfToGlbContractTests : TranslatorContractTests<ThreeMfToGlbTranslator> { }

/// <summary>See <see cref="ThreeMfToObjContractTests"/>.</summary>
public class GcodeToPngContractTests : TranslatorContractTests<GcodeToPngTranslator> { }

/// <summary>Builds tiny real inputs in-test so the full conversions run anywhere.</summary>
public static class Fixtures
{
    /// <summary>A unit cube as a minimal, spec-shaped 3MF model part.</summary>
    public const string CubeModelXml = """
        <?xml version="1.0" encoding="UTF-8"?>
        <model unit="millimeter" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">
          <resources>
            <object id="1" type="model">
              <mesh>
                <vertices>
                  <vertex x="0" y="0" z="0"/><vertex x="10" y="0" z="0"/>
                  <vertex x="10" y="10" z="0"/><vertex x="0" y="10" z="0"/>
                  <vertex x="0" y="0" z="10"/><vertex x="10" y="0" z="10"/>
                  <vertex x="10" y="10" z="10"/><vertex x="0" y="10" z="10"/>
                </vertices>
                <triangles>
                  <triangle v1="0" v2="1" v3="2"/><triangle v1="0" v2="2" v3="3"/>
                  <triangle v1="4" v2="6" v3="5"/><triangle v1="4" v2="7" v3="6"/>
                  <triangle v1="0" v2="4" v3="5"/><triangle v1="0" v2="5" v3="1"/>
                  <triangle v1="1" v2="5" v3="6"/><triangle v1="1" v2="6" v3="2"/>
                  <triangle v1="2" v2="6" v3="7"/><triangle v1="2" v2="7" v3="3"/>
                  <triangle v1="3" v2="7" v3="4"/><triangle v1="3" v2="4" v3="0"/>
                </triangles>
              </mesh>
            </object>
          </resources>
          <build><item objectid="1" transform="1 0 0 0 1 0 0 0 1 5 0 0"/></build>
        </model>
        """;

    /// <summary>Zips the model XML the way every slicer lays a 3MF out.</summary>
    public static Stream Cube3mf()
    {
        var ms = new MemoryStream();
        using (var zip = new ZipArchive(ms, ZipArchiveMode.Create, leaveOpen: true))
        {
            using var entry = zip.CreateEntry("3D/3dmodel.model").Open();
            entry.Write(Encoding.UTF8.GetBytes(CubeModelXml));
        }
        ms.Position = 0;
        return ms;
    }

    /// <summary>A 1×1 transparent PNG.</summary>
    public static readonly byte[] TinyPng = Convert.FromBase64String(
        "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==");

    /// <summary>G-code with two embedded thumbnails; the larger one must win.</summary>
    public static Stream GcodeWithThumbnails()
    {
        var b64 = Convert.ToBase64String(TinyPng);
        var text = $"""
            ; generated by OrcaSlicer
            ; thumbnail begin 16x16 {b64.Length}
            ; {b64}
            ; thumbnail end
            ; thumbnail begin 300x300 {b64.Length}
            ; {b64}
            ; thumbnail end
            G28 ; home
            G1 X10 Y10
            """;
        return new MemoryStream(Encoding.UTF8.GetBytes(text));
    }

    public static async Task<byte[]> Run(ITranslator t, Stream input)
    {
        await using var output = await t.TranslateAsync(input);
        using var ms = new MemoryStream();
        await output.CopyToAsync(ms);
        return ms.ToArray();
    }
}

/// <summary>Real conversions over the in-test fixtures.</summary>
public class ConversionTests
{
    [Fact]
    public async Task Obj_CarriesEveryVertexAndFace_WithTheBuildTransformApplied()
    {
        var bytes = await Fixtures.Run(new ThreeMfToObjTranslator(), Fixtures.Cube3mf());
        var lines = Encoding.ASCII.GetString(bytes).Split('\n');

        Assert.Equal(8, lines.Count(l => l.StartsWith("v ")));
        Assert.Equal(12, lines.Count(l => l.StartsWith("f ")));
        // The build item translates x by +5, so the cube spans 5..15 on x.
        Assert.Contains("v 5 0 0", lines);
        Assert.Contains("v 15 10 10", lines);
        // OBJ faces are 1-based.
        Assert.DoesNotContain(lines, l => l.StartsWith("f ") && l.Split(' ').Contains("0"));
    }

    [Fact]
    public async Task Glb_IsAValidTwoChunkContainer()
    {
        var bytes = await Fixtures.Run(new ThreeMfToGlbTranslator(), Fixtures.Cube3mf());

        Assert.Equal("glTF", Encoding.ASCII.GetString(bytes[..4]));
        Assert.Equal(2u, BitConverter.ToUInt32(bytes, 4));
        Assert.Equal((uint)bytes.Length, BitConverter.ToUInt32(bytes, 8));

        var jsonLength = BitConverter.ToUInt32(bytes, 12);
        Assert.Equal(0x4E4F534Au, BitConverter.ToUInt32(bytes, 16)); // 'JSON'
        var json = Encoding.UTF8.GetString(bytes, 20, (int)jsonLength);
        Assert.Contains("\"POSITION\":1", json);
        Assert.Contains("\"count\":36", json);  // 12 triangles × 3 indices
        Assert.Contains("\"count\":8", json);   // 8 vertices

        var binOffset = 20 + (int)jsonLength;
        Assert.Equal(0x004E4942u, BitConverter.ToUInt32(bytes, binOffset + 4)); // 'BIN'
    }

    [Fact]
    public async Task Gcode_ExtractsTheLargestThumbnail_AsRealPngBytes()
    {
        var bytes = await Fixtures.Run(new GcodeToPngTranslator(), Fixtures.GcodeWithThumbnails());

        Assert.Equal(Fixtures.TinyPng, bytes);
    }

    [Fact]
    public async Task Gcode_WithoutAThumbnail_SaysWhatToEnable()
    {
        using var input = new MemoryStream(Encoding.UTF8.GetBytes("G28\nG1 X1\n"));

        var ex = await Assert.ThrowsAsync<InvalidOperationException>(
            () => Fixtures.Run(new GcodeToPngTranslator(), input));

        Assert.Contains("thumbnail", ex.Message, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public async Task NotA3mf_FailsWithAnActionableMessage()
    {
        using var input = new MemoryStream(Encoding.UTF8.GetBytes("not a zip"));

        var ex = await Assert.ThrowsAsync<InvalidOperationException>(
            () => Fixtures.Run(new ThreeMfToObjTranslator(), input));

        Assert.Contains("3MF", ex.Message);
    }
}

/// <summary>Repo-level rules.</summary>
public class OrcaSlicerTranslatorSuiteTests
{
    private static readonly ITranslator[] All =
    [
        new ThreeMfToObjTranslator(),
        new ThreeMfToGlbTranslator(),
        new GcodeToPngTranslator(),
    ];

    /// <summary>The server's registry is first-wins on keys AND MIME pairs.</summary>
    [Fact]
    public void KeysAndMimePairsAreUniqueWithinTheRepo()
    {
        Assert.Equal(All.Length, All.Select(t => t.Key).Distinct().Count());
        Assert.Equal(All.Length, All.Select(t => (t.InputMimeType, t.OutputMimeType)).Distinct().Count());
    }

    /// <summary>The keys reserved in Nexus.PLM.Services/docs/translator-ownership.md. The
    /// mesh-to-mesh pairs deliberately do not collide with PrusaSlicer's (3mf→stl/png/gcode)
    /// or FreeCAD's (x-freecad inputs).</summary>
    [Fact]
    public void CarriesTheThreeReservedKeys() =>
        Assert.Equal(
            ["3mf_to_glb", "3mf_to_obj", "gcode_to_png"],
            All.Select(t => t.Key).OrderBy(k => k).ToArray());

    /// <summary>3MF is the catalog's name, never the vendor tree value.</summary>
    [Fact]
    public void UsesTheCatalogs3mfName() =>
        Assert.All(All.Where(t => t.Key.StartsWith("3mf")),
            t => Assert.Equal("model/3mf", t.InputMimeType));
}
